### ISSUE TITLE
Suggestion: reboot CLI after installing cloud

### ISSUE THREAD

**Issue by hoogvliets** [pugillum/eneco_docker_kubernetes_training_05_2024#1]
Add step after installing, new line 97 insert:

2. Reboot your terminal to make sure the next step will work (not needed on all terminals, but crucial for some)

New instructions would be:

> 1. Install `gcloud` for your particular platform: https://cloud.google.com/sdk/docs/install
> 2. Reboot your terminal to make sure the next step will work (not needed on all terminals, but crucial for some)
> 3. Link to your Google Cloud Platform account by running `gcloud auth login`
> 4. Install `kubectl` , instructions: [here](https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_kubectl)
> > Note: If you already have kubectl you can skip this step but you'll still need to install the plugin in the next step
> 5. Install the required `gke-gcloud-auth-plugin`, instructions [here](https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin)

**Comment by pugillum** [comment]
Thanks @hoogvliets , updated!
